/* myran.c - Testing random and initstate */
#include <stdio.h>
#include <stdlib.h>

#define SIZE 1000

void initrandom(unsigned seed){

  /* This function must be called before we can generate random numbers.

   * You can choose as seed any number, say, 1, 123, 357, ...

   */

#define RANDSIZE 256

  static char randstate[RANDSIZE];

  initstate(seed, randstate, RANDSIZE);

}


int myrandom(int low, int high){

  /* It returns a random number in the interval [low,high]

   */

  return (low + random()%(high-low+1)); /* this assumes that all the bits

                         of the number generated by random are

                         equally random, which is not true in

                         old implementations of random */

}


int main() {

  /* It generates and prints SIZE random numbers in the interval [10,20].

   * Then prints out their average (it should be close to 15).

   */

    int i;

    int table[SIZE];

    int sum = 0;

    initrandom(1357);

    for (i=0; i<SIZE; i++) {

      table[i] = myrandom(10,20);

      sum += table[i];

      printf("%2d\n", table[i]);

    }

    printf("the average is %f\n", sum/(float)SIZE);

    exit(0);

}




// If one is interested in generating random real numbers uniformly distributed in range 0.0 .. 1.0, assuming the inclusion of stdlib.h one can use the function

  /* returns a random real uniformly distributed in range 0 .. 1 */

  double rand01(void)

  {

     return ((random())/(double)RAND_MAX);

  }